## loaded and checking the data set

In [1]:
import pandas as pd
import polars as pl

In [2]:
df = pd.read_csv('cvd.csv')
df.head()

,PatientID,Age,Gender,BMI,Smoking,Alcohol,FamilyHistory,SystolicBP,DiastolicBP,HeartRate,Cholesterol,Glucose,OxygenSaturation,HRV,RRInterval,QTInterval,QRSDuration,PulseTransitTime,PPGAmplitude,DiseaseLabel
0,P0001,59,Male,28.8,No,No,No,110,78,76,225,93,97.1,56,791,395,80,236,1.96,0
1,P0002,50,Male,22.8,No,Moderate,Yes,139,74,70,241,125,97.4,52,895,365,92,240,1.63,0
2,P0003,61,Female,28.3,No,No,No,144,73,77,215,90,98.2,65,775,370,85,201,1.92,0
3,P0004,73,Female,34.1,No,Moderate,No,142,88,76,230,144,98.5,49,790,415,92,227,1.22,1
4,P0005,49,Male,29.8,Yes,No,No,145,89,77,245,131,96.8,37,758,374,101,198,1.82,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         1000 non-null   object
 1   Age               1000 non-null   int64
 2   Gender            1000 non-null   object
 3   BMI               1000 non-null   float64
 4   Smoking           1000 non-null   object
 5   Alcohol           1000 non-null   object
 6   FamilyHistory     1000 non-null   object
 7   SystolicBP        1000 non-null   int64
 8   DiastolicBP       1000 non-null   int64
 9   HeartRate         1000 non-null   int64
 10  Cholesterol       1000 non-null   int64
 11  Glucose           1000 non-null   int64
 12  OxygenSaturation  1000 non-null   float64
 13  HRV               1000 non-null   int64
 14  RRInterval        1000 non-null   int64
 15  QTInterval        1000 non-null   int64
 16  QRSDuration       1000 non-null   int64
 17  PulseTransitTime  1000 non-null   int64
 18  PPGAmplitude      1000 non-null   float64
 19  DiseaseLabel      1000 non-null   int64
dtypes: float64(3), int64(12), object(5)
memory usage: 156.4+ KB

In [4]:
df.describe()

,Age,BMI,SystolicBP,DiastolicBP,HeartRate,Cholesterol,Glucose,OxygenSaturation,HRV,RRInterval,QTInterval,QRSDuration,PulseTransitTime,PPGAmplitude,DiseaseLabel
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,52.294000,26.856200,139.298000,81.054000,75.116000,226.124000,107.366000,97.868100,57.1300,810.597000,389.362000,91.195000,211.378000,1.569270,0.442000
std,13.553939,4.608027,15.778852,9.312992,8.477996,29.406519,17.978244,0.864002,11.8869,102.218458,22.324501,8.845859,15.412614,0.280514,0.496873
min,20.000000,17.500000,95.000000,58.000000,48.000000,126.000000,65.000000,95.300000,18.0000,544.000000,320.000000,70.000000,158.000000,0.350000,0.000000
25%,43.000000,23.675000,129.000000,74.750000,69.000000,206.000000,95.000000,97.300000,49.0000,737.750000,375.000000,85.000000,201.000000,1.400000,0.000000
50%,52.000000,27.000000,139.000000,81.000000,75.000000,225.000000,107.000000,97.900000,57.0000,803.000000,389.000000,91.000000,212.000000,1.610000,0.000000
75%,61.000000,30.100000,150.000000,88.000000,81.000000,246.000000,120.000000,98.400000,65.0000,874.000000,404.000000,97.000000,222.000000,1.760000,1.000000
max,89.000000,41.800000,184.000000,113.000000,107.000000,311.000000,164.000000,100.000000,91.0000,1261.000000,468.000000,121.000000,260.000000,2.270000,1.000000

In [5]:
df.isnull().sum()

PatientID           0
Age                 0
Gender              0
BMI                 0
Smoking             0
Alcohol             0
FamilyHistory       0
SystolicBP          0
DiastolicBP         0
HeartRate           0
Cholesterol         0
Glucose             0
OxygenSaturation    0
HRV                 0
RRInterval          0
QTInterval          0
QRSDuration         0
PulseTransitTime    0
PPGAmplitude        0
DiseaseLabel        0
dtype: int64

In [6]:
# import pandas as pd
# import plotly.express as px

# # If df_clean is pandas (which it seems to be)
# num_cols = df.select_dtypes(include='number').columns.tolist()

# # Create box plot for all numeric columns
# fig = px.box(
#     df[num_cols], 
#     title="All Numeric Columns - Outlier Detection",
#     points="outliers",
#     width=1000,
#     height=600
# )

# fig.update_layout(
#     xaxis_title="Numeric Features",
#     yaxis_title="Value",
#     template="plotly_white"
# )

# fig.show()

In [7]:
# import plotly.express as px
# import os
# for i in df.columns:
    
#     fig = px.histogram(
#         df,
#         x=i,
#         color='DiseaseLabel',                    # Only two colors based on disease
#         title=f'{i} Distribution by DiseaseLabel Status',
#         labels={i: i, 'count': 'Number of Patients'},
#         color_discrete_map={
#             0: '#636EFA',   # BluDiseaseLabel
#             1: "#54F389"    # Red   - Has DiseaseLabel
#             # If your DiabetesLabel is 'No'/'Yes':
#             # 'No': '#636EFA', 'Yes': '#EF553B'
#         },
#         barmode='overlay',          # Overlapping for better comparison
#         opacity=0.75,               # Transparency to see overlapping bars
#         nbins=20,                   # Adjust number of bins as needed
#         text_auto=True              # Show count on bars
#     )

#     fig.update_layout(
#         xaxis_title=i,
#         yaxis_title='Number of Patients',
#         template='plotly_white',
#         height=560,
#         title_font_size=24,
#         title_x=0.5,                    # Center the title
#         legend_title_text='DiseaseLabel Status',
#         bargap=0.01,
#         barmode='overlay'
#     )

#     fig.update_traces(
#         marker_line_color='white',
#         marker_line_width=1
#     )

#     os.makedirs('features', exist_ok=True)
#     fig.show()
#     fig.write_image(f'features/{i}_DiseaseLabel_Status.png')

## clearning data set

In [8]:
df.isnull().sum(), df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         1000 non-null   object
 1   Age               1000 non-null   int64
 2   Gender            1000 non-null   object
 3   BMI               1000 non-null   float64
 4   Smoking           1000 non-null   object
 5   Alcohol           1000 non-null   object
 6   FamilyHistory     1000 non-null   object
 7   SystolicBP        1000 non-null   int64
 8   DiastolicBP       1000 non-null   int64
 9   HeartRate         1000 non-null   int64
 10  Cholesterol       1000 non-null   int64
 11  Glucose           1000 non-null   int64
 12  OxygenSaturation  1000 non-null   float64
 13  HRV               1000 non-null   int64
 14  RRInterval        1000 non-null   int64
 15  QTInterval        1000 non-null   int64
 16  QRSDuration       1000 non-null   int64
 17  PulseTransitTime  1000 non-null   int64
 18  PPGAmplitude      1000 non-null   float64
 19  DiseaseLabel      1000 non-null   int64
dtypes: float64(3), int64(12), object(5)
memory usage: 156.4+ KB

(PatientID           0
 Age                 0
 Gender              0
 BMI                 0
 Smoking             0
 Alcohol             0
 FamilyHistory       0
 SystolicBP          0
 DiastolicBP         0
 HeartRate           0
 Cholesterol         0
 Glucose             0
 OxygenSaturation    0
 HRV                 0
 RRInterval          0
 QTInterval          0
 QRSDuration         0
 PulseTransitTime    0
 PPGAmplitude        0
 DiseaseLabel        0
 dtype: int64,
 None)

In [9]:
cat_col = df.select_dtypes(include=('object')).columns

for i in cat_col:
    print(df[i].value_counts())

PatientID
P0001    1
P0002    1
P0003    1
P0004    1
P0005    1
        ..
P0996    1
P0997    1
P0998    1
P0999    1
P1000    1
Name: count, Length: 1000, dtype: int64
Gender
Male      509
Female    491
Name: count, dtype: int64
Smoking
No     787
Yes    213
Name: count, dtype: int64
Alcohol
Moderate    511
No          370
High        119
Name: count, dtype: int64
FamilyHistory
No     747
Yes    253
Name: count, dtype: int64

In [10]:
gender_mapping = {'Male': 1, 'Female': 0}
smoking_mapping = {'No': 0, 'Yes': 1}
alcohol_mapping = {'No': 0, 'Moderate': 1, 'High': 2}
family_mapping = {'No': 0, 'Yes': 1}


df['Gender'] = df['Gender'].map(gender_mapping)
df['Smoking'] = df['Smoking'].map(smoking_mapping)
df['Alcohol'] = df['Alcohol'].map(alcohol_mapping)
df['FamilyHistory'] = df['FamilyHistory'].map(family_mapping)

In [11]:
df.head()

,PatientID,Age,Gender,BMI,Smoking,Alcohol,FamilyHistory,SystolicBP,DiastolicBP,HeartRate,Cholesterol,Glucose,OxygenSaturation,HRV,RRInterval,QTInterval,QRSDuration,PulseTransitTime,PPGAmplitude,DiseaseLabel
0,P0001,59,1,28.8,0,0,0,110,78,76,225,93,97.1,56,791,395,80,236,1.96,0
1,P0002,50,1,22.8,0,1,1,139,74,70,241,125,97.4,52,895,365,92,240,1.63,0
2,P0003,61,0,28.3,0,0,0,144,73,77,215,90,98.2,65,775,370,85,201,1.92,0
3,P0004,73,0,34.1,0,1,0,142,88,76,230,144,98.5,49,790,415,92,227,1.22,1
4,P0005,49,1,29.8,1,0,0,145,89,77,245,131,96.8,37,758,374,101,198,1.82,1

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         1000 non-null   object
 1   Age               1000 non-null   int64
 2   Gender            1000 non-null   int64
 3   BMI               1000 non-null   float64
 4   Smoking           1000 non-null   int64
 5   Alcohol           1000 non-null   int64
 6   FamilyHistory     1000 non-null   int64
 7   SystolicBP        1000 non-null   int64
 8   DiastolicBP       1000 non-null   int64
 9   HeartRate         1000 non-null   int64
 10  Cholesterol       1000 non-null   int64
 11  Glucose           1000 non-null   int64
 12  OxygenSaturation  1000 non-null   float64
 13  HRV               1000 non-null   int64
 14  RRInterval        1000 non-null   int64
 15  QTInterval        1000 non-null   int64
 16  QRSDuration       1000 non-null   int64
 17  PulseTransitTime  1000 non-null   int64
 18  PPGAmplitude      1000 non-null   float64
 19  DiseaseLabel      1000 non-null   int64
dtypes: float64(3), int64(16), object(1)
memory usage: 156.4+ KB

## model working

In [13]:
df.isnull().sum()

PatientID           0
Age                 0
Gender              0
BMI                 0
Smoking             0
Alcohol             0
FamilyHistory       0
SystolicBP          0
DiastolicBP         0
HeartRate           0
Cholesterol         0
Glucose             0
OxygenSaturation    0
HRV                 0
RRInterval          0
QTInterval          0
QRSDuration         0
PulseTransitTime    0
PPGAmplitude        0
DiseaseLabel        0
dtype: int64

In [14]:
x = df.drop(['DiseaseLabel', 'PatientID'], axis=1)
y = df['DiseaseLabel']

In [15]:
x

,Age,Gender,BMI,Smoking,Alcohol,FamilyHistory,SystolicBP,DiastolicBP,HeartRate,Cholesterol,Glucose,OxygenSaturation,HRV,RRInterval,QTInterval,QRSDuration,PulseTransitTime,PPGAmplitude
0,59,1,28.8,0,0,0,110,78,76,225,93,97.1,56,791,395,80,236,1.96
1,50,1,22.8,0,1,1,139,74,70,241,125,97.4,52,895,365,92,240,1.63
2,61,0,28.3,0,0,0,144,73,77,215,90,98.2,65,775,370,85,201,1.92
3,73,0,34.1,0,1,0,142,88,76,230,144,98.5,49,790,415,92,227,1.22
4,49,1,29.8,1,0,0,145,89,77,245,131,96.8,37,758,374,101,198,1.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,48,1,28.3,0,1,1,138,77,71,198,116,98.5,76,865,383,95,195,1.33
996,77,1,19.8,0,1,0,140,85,63,208,104,97.4,47,968,394,100,199,1.55
997,61,1,22.7,0,0,0,145,87,58,193,103,97.4,66,1004,390,91,207,1.74
998,44,1,40.0,0,2,0,130,80,90,221,106,98.2,58,583,386,91,204,1.02
999,60,1,25.9,0,0,0,144,87,64,221,121,97.9,71,950,386,106,226,2.10

In [16]:
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from xgboost.sklearn import XGBClassifier
from imblearn.over_sampling import SMOTE
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
import numpy as np

In [17]:
X_train, X_test, y_train , y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [18]:
scaled = StandardScaler()
X_train = scaled.fit_transform(X_train)
X_test = scaled.transform(X_test)

In [19]:
models = {
    "Logistic Regression": LogisticRegression(
        class_weight="balanced", max_iter=1000, random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=100, class_weight="balanced", random_state=42
    ),
    "XGBoost": XGBClassifier(
        n_estimators=100, scale_pos_weight=1,
        use_label_encoder=False, eval_metric="logloss",
        random_state=42, verbosity=0
    ),
    # "SVM": SVC(
    #     kernel="rbf", class_weight="balanced",
    #     probability=True, random_state=42
    # ),
    "KNN": KNeighborsClassifier(n_neighbors=5),

    "dt":DecisionTreeClassifier(criterion='log_loss',max_depth=20),

    "grdi":GradientBoostingClassifier(learning_rate=0.001, n_estimators=100, min_samples_split=0.2),

    'gnb':GaussianNB(var_smoothing=1e-9)
}

In [20]:
# skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
# cv_results = {}
 
# for name, model in models.items():
#     cv_scores = cross_val_score(
#         model, X_train, y_train,
#         cv=skf, scoring="roc_auc", n_jobs=-1
#     )
#     cv_results[name] = cv_scores
#     print(f"\n{name}:")
#     print(f"  CV Accuracy Scores : {cv_results[name]}")
#     print(f"  CV ROC-AUC Scores : {cv_scores.round(4)}")
#     print(f"  Mean  ± Std       : {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

In [21]:
from sklearn.metrics          import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix,
    classification_report, roc_curve
)

In [22]:
 
results = {}
best_model_name = None
best_auc = 0
 
for name, model in models.items():
    print(f"\n{'─'*50}")
    print(f"Model: {name}")
    print(f"{'─'*50}")
 
    # Train
    model.fit(X_train, y_train)

    from sklearn.inspection import permutation_importance

    result = permutation_importance(
        model, X_test, y_test,
        n_repeats=10,
        random_state=42,
        scoring='roc_auc'
    )

    perm_df = pd.DataFrame({
        'Feature':   x.columns,
        'Importance': result.importances_mean,
        'Std':        result.importances_std
    }).sort_values('Importance', ascending=False)

    # print(perm_df)
 
    # Predict
    y_pred      = model.predict(X_test)
    y_pred_prob = model.predict_proba(X_test)[:, 1]
 
    # Metrics
    acc  = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec  = recall_score(y_test, y_pred, zero_division=0)
    f1   = f1_score(y_test, y_pred, zero_division=0)
    auc  = roc_auc_score(y_test, y_pred_prob)
    cm   = confusion_matrix(y_test, y_pred)
    fpr, tpr, _ = roc_curve(y_test, y_pred_prob)
 
    results[name] = {
        "Accuracy" : round(acc,  4),
        "Precision": round(prec, 4),
        "Recall"   : round(rec,  4),
        "F1-Score" : round(f1,   4),
        "fpr"  : fpr,
        "tpr"  : tpr,
        # "CV Mean"  : round(cv_results[name].mean(), 4),
        # "CV Std"   : round(cv_results[name].std(),  4),
    }
 
    print(f"  Accuracy  : {acc:.4f}")
    print(f"  Precision : {prec:.4f}")
    print(f"  Recall    : {rec:.4f}")
    print(f"  F1-Score  : {f1:.4f}")
    print(f"  ROC-AUC   : {auc:.4f}")
    print(f"\n  Confusion Matrix:\n{cm}")
    print(f"\n  Classification Report:\n{classification_report(y_test, y_pred)}")
 
    # Track best model
    if auc > best_auc:
        best_auc = auc
        best_model_name = name

──────────────────────────────────────────────────
Model: Logistic Regression
──────────────────────────────────────────────────
  Accuracy  : 0.8100
  Precision : 0.8000
  Recall    : 0.7704
  F1-Score  : 0.7849
  ROC-AUC   : 0.8873

  Confusion Matrix:
[[139  26]
 [ 31 104]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.84      0.83       165
           1       0.80      0.77      0.78       135

    accuracy                           0.81       300
   macro avg       0.81      0.81      0.81       300
weighted avg       0.81      0.81      0.81       300


──────────────────────────────────────────────────
Model: Random Forest
──────────────────────────────────────────────────
  Accuracy  : 0.8000
  Precision : 0.8099
  Recall    : 0.7259
  F1-Score  : 0.7656
  ROC-AUC   : 0.8693

  Confusion Matrix:
[[142  23]
 [ 37  98]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.86      0.83       165
           1       0.81      0.73      0.77       135

    accuracy                           0.80       300
   macro avg       0.80      0.79      0.80       300
weighted avg       0.80      0.80      0.80       300


──────────────────────────────────────────────────
Model: XGBoost
──────────────────────────────────────────────────
  Accuracy  : 0.7667
  Precision : 0.7519
  Recall    : 0.7185
  F1-Score  : 0.7348
  ROC-AUC   : 0.8362

  Confusion Matrix:
[[133  32]
 [ 38  97]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.81      0.79       165
           1       0.75      0.72      0.73       135

    accuracy                           0.77       300
   macro avg       0.76      0.76      0.76       300
weighted avg       0.77      0.77      0.77       300


──────────────────────────────────────────────────
Model: KNN
──────────────────────────────────────────────────
  Accuracy  : 0.7633
  Precision : 0.7712
  Recall    : 0.6741
  F1-Score  : 0.7194
  ROC-AUC   : 0.8280

  Confusion Matrix:
[[138  27]
 [ 44  91]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.84      0.80       165
           1       0.77      0.67      0.72       135

    accuracy                           0.76       300
   macro avg       0.76      0.76      0.76       300
weighted avg       0.76      0.76      0.76       300


──────────────────────────────────────────────────
Model: dt
──────────────────────────────────────────────────
  Accuracy  : 0.7467
  Precision : 0.7323
  Recall    : 0.6889
  F1-Score  : 0.7099
  ROC-AUC   : 0.7414

  Confusion Matrix:
[[131  34]
 [ 42  93]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.79      0.78       165
           1       0.73      0.69      0.71       135

    accuracy                           0.75       300
   macro avg       0.74      0.74      0.74       300
weighted avg       0.75      0.75      0.75       300


──────────────────────────────────────────────────
Model: grdi
──────────────────────────────────────────────────
  Accuracy  : 0.5500
  Precision : 0.0000
  Recall    : 0.0000
  F1-Score  : 0.0000
  ROC-AUC   : 0.8130

  Confusion Matrix:
[[165   0]
 [135   0]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.55      1.00      0.71       165
           1       0.00      0.00      0.00       135

    accuracy                           0.55       300
   macro avg       0.28      0.50      0.35       300
weighted avg       0.30      0.55      0.39       300


──────────────────────────────────────────────────
Model: gnb
──────────────────────────────────────────────────

c:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

  Accuracy  : 0.7833
  Precision : 0.7778
  Recall    : 0.7259
  F1-Score  : 0.7510
  ROC-AUC   : 0.8846

  Confusion Matrix:
[[137  28]
 [ 37  98]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.83      0.81       165
           1       0.78      0.73      0.75       135

    accuracy                           0.78       300
   macro avg       0.78      0.78      0.78       300
weighted avg       0.78      0.78      0.78       300

In [23]:
import plotly.graph_objects as go
from sklearn.metrics import auc

for model_name, data in results.items():

    fpr = data['fpr']
    tpr = data['tpr']

    # Skip invalid
    if len(fpr) == 0 or len(tpr) == 0:
        continue

    roc_auc = auc(fpr, tpr)

    # 🔥 NEW FIGURE for each model
    fig = go.Figure()

    # ROC curve
    fig.add_trace(go.Scatter(
        x=fpr,
        y=tpr,
        mode='lines',
        name=f"AUC = {roc_auc:.3f}"
    ))

    # Random line
    fig.add_trace(go.Scatter(
        x=[0, 1],
        y=[0, 1],
        mode='lines',
        line=dict(dash='dash'),
        name='Random'
    ))

    fig.update_layout(
        title=f"ROC Curve - {model_name}",
        xaxis_title="False Positive Rate",
        yaxis_title="True Positive Rate",
        width=700,
        height=500
    )
    # fig.write_image(f"roc curve/ROC_Curve_{model_name}.png")
    fig.show()

In [24]:
perm_df

             Feature  Importance       Std
10           Glucose    0.013149  0.003055
0                Age    0.012377  0.003273
6         SystolicBP    0.011196  0.004423
9        Cholesterol    0.008494  0.004786
3            Smoking    0.008391  0.004056
17      PPGAmplitude    0.008094  0.003104
7        DiastolicBP    0.007874  0.004972
12               HRV    0.006590  0.002714
5      FamilyHistory    0.006527  0.001046
2                BMI    0.002882  0.003198
11  OxygenSaturation    0.001863  0.002679
16  PulseTransitTime    0.000314  0.002347
4            Alcohol    0.000211  0.000477
1             Gender    0.000135  0.000040
15       QRSDuration   -0.000076  0.002276
14        QTInterval   -0.000866  0.002549
8          HeartRate   -0.001028  0.003058
13        RRInterval   -0.002101  0.003943

In [25]:
best_model_name

'Logistic Regression'

In [26]:
# import plotly.graph_objects as go

# features    = perm_df['Feature']
# importance  = perm_df['Importance']
# std         = perm_df['Std']

# colors = [f'rgba(55,138,221,{round(1 - i*0.09, 2)})' for i in range(len(features))]

In [52]:
import plotly.graph_objects as go
import pandas as pd
import os

# Assuming perm_df is your existing DataFrame
features    = perm_df['Feature']
importance  = perm_df['Importance']
std         = perm_df['Std']

# --- COLOR FIX ---
# This logic ensures the alpha channel never goes below 0.0
colors = [f'rgba(55, 138, 221, {max(0, round(1 - i * 0.09, 2))})' for i in range(len(features))]

fig1 = go.Figure(go.Bar(
    x=importance,
    y=features,
    orientation='h',
    marker_color=colors,
    text=[f"{v:.4f}" for v in importance],
    textposition='outside',
    cliponaxis=False,
))

fig1.update_layout(
    title="Feature Importance — Horizontal Bar",
    xaxis_title="Importance score",
    # Added a check for max(importance) to handle empty data gracefully
    xaxis=dict(range=[0, (max(importance) if len(importance) > 0 else 1) * 1.2]),
    yaxis=dict(categoryorder='total ascending'),
    template='plotly_white',
    height=450,
    showlegend=False,
    margin=dict(l=20, r=50, t=50, b=50) # Added right margin so text isn't cut off
)

# --- DIRECTORY FIX ---
# Create the folder if it doesn't exist to prevent write_image from failing
output_dir = "perm_for_features"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Save and show
fig1.write_image(f"{output_dir}/importance_horizontal_bar.png", width=1500, height=450, scale=2)
fig1.show()

In [53]:
fig2 = go.Figure(go.Bar(
    x=importance,
    y=features,
    orientation='h',
    marker_color=colors,
    text=[f"{v:.4f}" for v in importance],
    textposition='outside',
    cliponaxis=False,
    error_x=dict(
        type='data',
        array=std,
        visible=True,
        color='#e24b4a',
        thickness=2,
        width=6,
    ),
))

fig2.update_layout(
    title="Feature Importance — With Std Error Bars",
    xaxis_title="Importance ± Std Error",
    xaxis=dict(range=[0, max(importance) * 1.25]),
    yaxis=dict(categoryorder='total ascending'),
    template='plotly_white',
    height=450,
    showlegend=False,
)

fig2.write_image("perm_for_features/error_bars.png", width=1500, height=450, scale=2)
fig2.show()

In [54]:
fig3 = go.Figure()

# stems (lines from 0 to dot)
for i, (feat, val) in enumerate(zip(features, importance)):
    fig3.add_shape(
        type='line',
        x0=0, x1=val,
        y0=feat, y1=feat,
        line=dict(color='#b5d4f4', width=2),
    )

# dots
fig3.add_trace(go.Scatter(
    x=importance,
    y=features,
    mode='markers+text',
    marker=dict(size=14, color=colors, line=dict(width=1, color='white')),
    text=[f"{v:.4f}" for v in importance],
    textposition='middle right',
    textfont=dict(size=11),
))

fig3.update_layout(
    title="Feature Importance — Dot / Lollipop Chart",
    xaxis_title="Importance score",
    xaxis=dict(range=[-0.002, max(importance) * 1.3]),
    yaxis=dict(categoryorder='array', categoryarray=features),
    template='plotly_white',
    height=450,
    showlegend=False,
)

fig3.write_image("perm_for_features/dot_plot.png", width=1500, height=450, scale=2)
fig3.show()

## model combination

In [48]:
import plotly.graph_objects as go
from sklearn.metrics import auc

# 1. Ensure ROC-AUC is a single number, not an array
for model in results:
    if "fpr" in results[model] and "tpr" in results[model]:
        results[model]["ROC-AUC"] = auc(results[model]["fpr"], results[model]["tpr"])

# 2. Setup Radar Chart
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC']
metrics_closed = metrics + [metrics[0]]
models = list(results.keys())
colors = ['#636EFA', '#EF553B', '#00CC96', '#AB63FA']

fig3 = go.Figure()

for model, color in zip(models, colors):
    # Pull the single values for each metric
    vals = [results[model].get(m, 0) for m in metrics]
    vals_closed = vals + [vals[0]] # Close the loop
    
    fig3.add_trace(go.Scatterpolar(
        r=vals_closed,
        theta=metrics_closed,
        fill='toself',
        name=model,
        line=dict(color=color)
    ))

fig3.update_layout(
    title="Model Comparison — Radar Chart",
    polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
    showlegend=True,
    template='plotly_white'
)
fig3.write_image("model_scoring/model_radar.png", width=1500, height=530, scale=2)
fig3.show()

In [49]:
fig1 = go.Figure()
 
for metric in metrics:
    fig1.add_trace(go.Bar(
        name=metric,
        y=models,  # swap here
        x=[results[m][metric] for m in models],  # swap here
        orientation='h',  # 🔥 important
        text=[f"{results[m][metric]:.2%}" for m in models],
        textposition='outside',
        textfont=dict(size=10),
    ))

fig1.update_layout(
    title="Model Comparison — All Metrics",
    barmode='group',
    xaxis=dict(range=[0, 1.15], tickformat='.0%', title='Score'),  # now x-axis is score
    yaxis_title='ML Model',
    legend=dict(orientation='h', yanchor='bottom', y=1.02, x=0),
    height=550,
)

fig1.write_image("model_scoring/model_grouped_bar.png", width=1500, height=450, scale=2)

In [50]:
import numpy as np

z = [[results[m][metric] for m in models] for metric in metrics]

fig2 = go.Figure(go.Heatmap(
    z=z,
    x=models,
    y=metrics,
    colorscale='Blues',
    zmin=0, zmax=1,
    text=[[f"{v:.3f}" for v in row] for row in z],
    texttemplate="%{text}",
    textfont=dict(size=12),
    colorbar=dict(title='Score', tickformat='.0%'),
))

fig2.update_layout(
    title="Model vs Metric Heatmap",
    xaxis_title='Model',
    yaxis_title='Metric',
    height=400,
    template='plotly_white',
)

fig2.write_image("model_scoring/model_heatmap.png",width=1500, height=450, scale=2)
print("Saved: chart2_heatmap.png")

Saved: chart2_heatmap.png

In [51]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig4 = make_subplots(
    rows=2, cols=3,
    subplot_titles=metrics,
    vertical_spacing=0.18,
    horizontal_spacing=0.08,
)

positions = [(1,1),(1,2),(1,3),(2,1),(2,2)]

for (row, col), metric in zip(positions, metrics):
    vals = [results[m][metric] for m in models]
    fig4.add_trace(
        go.Bar(
            x=models,
            y=vals,
            marker_color=colors,
            text=[f"{v:.2f}" for v in vals],
            textposition='outside',
            showlegend=False,
        ),
        row=row, col=col,
    )
    fig4.update_yaxes(range=[0, 1.15], tickformat='.0%', row=row, col=col)

fig4.update_layout(
    title="Per-Metric Breakdown",
    height=700,
    template='plotly_white',
)

fig4.write_image("model_scoring/model_subplots.png", width=1500, height=450, scale=2)
print("Saved: chart4_subplots.png")

Saved: chart4_subplots.png

In [34]:
perm_df

             Feature  Importance       Std
10           Glucose    0.013149  0.003055
0                Age    0.012377  0.003273
6         SystolicBP    0.011196  0.004423
9        Cholesterol    0.008494  0.004786
3            Smoking    0.008391  0.004056
17      PPGAmplitude    0.008094  0.003104
7        DiastolicBP    0.007874  0.004972
12               HRV    0.006590  0.002714
5      FamilyHistory    0.006527  0.001046
2                BMI    0.002882  0.003198
11  OxygenSaturation    0.001863  0.002679
16  PulseTransitTime    0.000314  0.002347
4            Alcohol    0.000211  0.000477
1             Gender    0.000135  0.000040
15       QRSDuration   -0.000076  0.002276
14        QTInterval   -0.000866  0.002549
8          HeartRate   -0.001028  0.003058
13        RRInterval   -0.002101  0.003943

In [35]:
from sklearn.metrics import mutual_info_score
from scipy.stats import entropy
import numpy as np
import pandas as pd

In [36]:
def feature_divergence(X, y):
    classes = np.unique(y)
    c1, c2 = classes[0], classes[1]
    
    divergence_scores = {}

    for col in X.columns:
        # Get probability distributions
        p = X[y == c1][col].value_counts(normalize=True)
        q = X[y == c2][col].value_counts(normalize=True)
        
        # Align indexes
        all_idx = p.index.union(q.index)
        p = p.reindex(all_idx, fill_value=1e-9)
        q = q.reindex(all_idx, fill_value=1e-9)
        
        # KL divergence
        kl_div = entropy(p, q)
        
        divergence_scores[col] = kl_div

    return pd.DataFrame(divergence_scores.items(), columns=['Feature', 'Divergence'])

In [37]:
from sklearn.feature_selection import mutual_info_classif

In [38]:
mi_scores = mutual_info_classif(x, y)

mi_df = pd.DataFrame({
    'Feature': x.columns,
    'MI Score': mi_scores
})

In [39]:
def goodness_factor(div_df, mi_df):
    result = pd.merge(div_df, mi_df, on='Feature')
    result['Goodness Factor (G)'] = result['Divergence'] * result['MI Score']
    return result

In [40]:
# Step 1: Divergence
div_df = feature_divergence(x, y)

# Step 2: Mutual Information
mi_scores = mutual_info_classif(x, y)
mi_df = pd.DataFrame({
    'Feature': x.columns,
    'MI Score': mi_scores
})

# Step 3: Goodness Factor
final_df = goodness_factor(div_df, mi_df)

print(final_df.sort_values(by='Goodness Factor (G)', ascending=False))

             Feature  Divergence  MI Score  Goodness Factor (G)
13        RRInterval    6.015975  0.052820             0.317762
6         SystolicBP    2.254130  0.130974             0.295231
10           Glucose    2.125070  0.121634             0.258480
9        Cholesterol    2.605008  0.097426             0.253795
0                Age    1.637889  0.094461             0.154716
12               HRV    1.388300  0.084060             0.116701
2                BMI    2.265216  0.050052             0.113378
17      PPGAmplitude    1.470324  0.065046             0.095639
7        DiastolicBP    1.035686  0.084761             0.087786
11  OxygenSaturation    0.853506  0.083040             0.070875
16  PulseTransitTime    1.032118  0.066942             0.069092
14        QTInterval    1.612285  0.030917             0.049847
8          HeartRate    0.444643  0.045747             0.020341
15       QRSDuration    0.447240  0.043196             0.019319
3            Smoking    0.137220  0.026685             0.003662
5      FamilyHistory    0.071958  0.046906             0.003375
1             Gender    0.002119  0.000000             0.000000
4            Alcohol    0.004341  0.000000             0.000000

In [55]:
import plotly.express as px

# Sort by Goodness Factor
final_df_sorted = final_df.sort_values(
    by="Goodness Factor (G)", ascending=False
)

fig = px.scatter(
    final_df_sorted,
    x="Feature",
    y="Goodness Factor (G)",
    color="Goodness Factor (G)",
    size="Goodness Factor (G)",
    size_max=30,
    color_continuous_scale="viridis",
    
    title="📊 Goodness Factor Between Features of CVD Dataset",
    
    labels={
        "Feature": "Features",
        "Goodness Factor (G)": "Goodness Factor Score"
    }
)

fig.update_traces(
    mode='lines+markers',
    marker=dict(line=dict(width=1.5, color='black')),
    line=dict(width=2),
    hovertemplate="<b>%{x}</b><br>G: %{y:.4f}<extra></extra>"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    xaxis=dict(tickangle=-45),
    hovermode="x unified"
)

fig.show()
fig.write_image("perm_for_features/Goodness Factor Score.png", width=1500, height=450, scale=2)

In [42]:
import plotly.express as px

fig = px.scatter(
    final_df_sorted,
    x="Feature",
    y="Goodness Factor (G)",
    color="Goodness Factor (G)",
    size="Goodness Factor (G)",
    title="Goodness Factor between Features of CVD Data"

)

fig.update_traces(mode='lines+markers')

fig.update_layout(
    template="plotly_white"
)

fig.update_xaxes(tickangle=-45)

fig.show()

In [56]:
import plotly.express as px

# Sort by Goodness Factor
final_df_sorted = final_df.sort_values(
    by="Goodness Factor (G)", ascending=False
)

fig = px.scatter(
    final_df_sorted,
    x="Feature",
    y="Divergence",
    color="Divergence",
    size="Divergence",
    size_max=30,
    color_continuous_scale="plasma",
    
    title="📊 Divergence Factor Between Features of CVD Dataset",
    
    labels={
        "Feature": "Features",
        "Divergence Factor (G)": "Divergence Factor Score"
    }
)

fig.update_traces(
    mode='lines+markers',
    marker=dict(line=dict(width=1.5, color='black')),
    line=dict(width=2),
    hovertemplate="<b>%{x}</b><br>G: %{y:.4f}<extra></extra>"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    xaxis=dict(tickangle=-45),
    hovermode="x unified"
)

fig.show()
fig.write_image("perm_for_features/Divergence Factor Score.png", width=1500, height=450, scale=2)

In [44]:
import plotly.express as px

fig = px.scatter(
    final_df_sorted,
    x="Feature",
    y="Divergence",
    color="Divergence",
    size="Divergence",
    title="Divergence Factor between Features of CVD Data"

)

fig.update_traces(mode='lines+markers')

fig.update_layout(
    template="plotly_white"
)

fig.update_xaxes(tickangle=-45)

fig.show()