## loaded and checking the data set

In [1]:
import pandas as pd
import polars as pl

In [2]:
df = pd.read_csv('ckd.csv')
df.head()

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,...,Itching,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis,DoctorInCharge
0,1,71,0,0,0,2,31.069414,1,5.128112,1.676220,...,7.556302,76.076800,0,0,1,1.018824,4.966808,9.871449,1,Confidential
1,2,34,0,0,1,3,29.692119,1,18.609552,8.377574,...,6.836766,40.128498,0,0,0,3.923538,8.189275,7.161765,1,Confidential
2,3,80,1,1,0,1,37.394822,1,11.882429,9.607401,...,2.144722,92.872842,0,1,1,1.429906,7.624028,7.354632,1,Confidential
3,4,40,0,2,0,1,31.329680,0,16.020165,0.408871,...,7.077188,90.080321,0,0,0,3.226416,3.282688,6.629587,1,Confidential
4,5,43,0,1,1,2,23.726311,0,7.944146,0.780319,...,3.553118,5.258372,0,0,1,0.285466,3.849498,1.437385,1,Confidential

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1659 entries, 0 to 1658
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PatientID                      1659 non-null   int64
 1   Age                            1659 non-null   int64
 2   Gender                         1659 non-null   int64
 3   Ethnicity                      1659 non-null   int64
 4   SocioeconomicStatus            1659 non-null   int64
 5   EducationLevel                 1659 non-null   int64
 6   BMI                            1659 non-null   float64
 7   Smoking                        1659 non-null   int64
 8   AlcoholConsumption             1659 non-null   float64
 9   PhysicalActivity               1659 non-null   float64
 10  DietQuality                    1659 non-null   float64
 11  SleepQuality                   1659 non-null   float64
 12  FamilyHistoryKidneyDisease     1659 non-null   int64
 13  FamilyHistoryHypertension      1659 non-null   int64
 14  FamilyHistoryDiabetes          1659 non-null   int64
 15  PreviousAcuteKidneyInjury      1659 non-null   int64
 16  UrinaryTractInfections         1659 non-null   int64
 17  SystolicBP                     1659 non-null   int64
 18  DiastolicBP                    1659 non-null   int64
 19  FastingBloodSugar              1659 non-null   float64
 20  HbA1c                          1659 non-null   float64
 21  SerumCreatinine                1659 non-null   float64
 22  BUNLevels                      1659 non-null   float64
 23  GFR                            1659 non-null   float64
 24  ProteinInUrine                 1659 non-null   float64
 25  ACR                            1659 non-null   float64
 26  SerumElectrolytesSodium        1659 non-null   float64
 27  SerumElectrolytesPotassium     1659 non-null   float64
 28  SerumElectrolytesCalcium       1659 non-null   float64
 29  SerumElectrolytesPhosphorus    1659 non-null   float64
 30  HemoglobinLevels               1659 non-null   float64
 31  CholesterolTotal               1659 non-null   float64
 32  CholesterolLDL                 1659 non-null   float64
 33  CholesterolHDL                 1659 non-null   float64
 34  CholesterolTriglycerides       1659 non-null   float64
 35  ACEInhibitors                  1659 non-null   int64
 36  Diuretics                      1659 non-null   int64
 37  NSAIDsUse                      1659 non-null   float64
 38  Statins                        1659 non-null   int64
 39  AntidiabeticMedications        1659 non-null   int64
 40  Edema                          1659 non-null   int64
 41  FatigueLevels                  1659 non-null   float64
 42  NauseaVomiting                 1659 non-null   float64
 43  MuscleCramps                   1659 non-null   float64
 44  Itching                        1659 non-null   float64
 45  QualityOfLifeScore             1659 non-null   float64
 46  HeavyMetalsExposure            1659 non-null   int64
 47  OccupationalExposureChemicals  1659 non-null   int64
 48  WaterQuality                   1659 non-null   int64
 49  MedicalCheckupsFrequency       1659 non-null   float64
 50  MedicationAdherence            1659 non-null   float64
 51  HealthLiteracy                 1659 non-null   float64
 52  Diagnosis                      1659 non-null   int64
 53  DoctorInCharge                 1659 non-null   object
dtypes: float64(30), int64(23), object(1)
memory usage: 700.0+ KB

In [4]:
df.describe()

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,...,MuscleCramps,Itching,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis
count,1659.000000,1659.000000,1659.000000,1659.00000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,...,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000
mean,830.000000,54.441230,0.515371,0.71308,0.977697,1.693189,27.620049,0.292948,9.969831,5.024247,...,3.525510,5.054869,49.730659,0.044002,0.103074,0.197107,2.000336,4.947788,5.144973,0.918626
std,479.056364,20.549757,0.499914,1.00043,0.776686,0.910611,7.288670,0.455252,5.798787,2.866274,...,2.026131,2.880460,27.827593,0.205162,0.304147,0.397934,1.141635,2.869959,2.901138,0.273492
min,1.000000,20.000000,0.000000,0.00000,0.000000,0.000000,15.033888,0.000000,0.021740,0.001186,...,0.006327,0.013697,0.087256,0.000000,0.000000,0.000000,0.001082,0.005392,0.004436,0.000000
25%,415.500000,36.000000,0.000000,0.00000,0.000000,1.000000,21.471449,0.000000,5.051156,2.555038,...,1.820793,2.532867,26.991708,0.000000,0.000000,0.000000,1.005802,2.498119,2.569561,1.000000
50%,830.000000,54.000000,1.000000,0.00000,1.000000,2.000000,27.652077,0.000000,9.951503,5.072395,...,3.572522,5.087086,48.970075,0.000000,0.000000,0.000000,2.040635,4.974069,5.182949,1.000000
75%,1244.500000,72.000000,1.000000,1.00000,2.000000,2.000000,34.015849,1.000000,14.967100,7.460563,...,5.254956,7.552093,73.913997,0.000000,0.000000,0.000000,2.947213,7.499783,7.733253,1.000000
max,1659.000000,90.000000,1.000000,3.00000,2.000000,3.000000,39.993532,1.000000,19.992713,9.998167,...,6.984636,9.998313,99.987510,1.000000,1.000000,1.000000,3.999469,9.992345,9.993754,1.000000

In [5]:
df.isnull().sum()

PatientID                        0
Age                              0
Gender                           0
Ethnicity                        0
SocioeconomicStatus              0
EducationLevel                   0
BMI                              0
Smoking                          0
AlcoholConsumption               0
PhysicalActivity                 0
DietQuality                      0
SleepQuality                     0
FamilyHistoryKidneyDisease       0
FamilyHistoryHypertension        0
FamilyHistoryDiabetes            0
PreviousAcuteKidneyInjury        0
UrinaryTractInfections           0
SystolicBP                       0
DiastolicBP                      0
FastingBloodSugar                0
HbA1c                            0
SerumCreatinine                  0
BUNLevels                        0
GFR                              0
ProteinInUrine                   0
ACR                              0
SerumElectrolytesSodium          0
SerumElectrolytesPotassium       0
SerumElectrolytesCalcium         0
SerumElectrolytesPhosphorus      0
HemoglobinLevels                 0
CholesterolTotal                 0
CholesterolLDL                   0
CholesterolHDL                   0
CholesterolTriglycerides         0
ACEInhibitors                    0
Diuretics                        0
NSAIDsUse                        0
Statins                          0
AntidiabeticMedications          0
Edema                            0
FatigueLevels                    0
NauseaVomiting                   0
MuscleCramps                     0
Itching                          0
QualityOfLifeScore               0
HeavyMetalsExposure              0
OccupationalExposureChemicals    0
WaterQuality                     0
MedicalCheckupsFrequency         0
MedicationAdherence              0
HealthLiteracy                   0
Diagnosis                        0
DoctorInCharge                   0
dtype: int64

In [6]:
import pandas as pd
import plotly.express as px

# If df_clean is pandas (which it seems to be)
num_cols = df.select_dtypes(include='number').columns.tolist()

# Create box plot for all numeric columns
fig = px.box(
    df[num_cols], 
    title="All Numeric Columns - Outlier Detection",
    points="outliers",
    width=1000,
    height=600
)

fig.update_layout(
    xaxis_title="Numeric Features",
    yaxis_title="Value",
    template="plotly_white"
)

fig.show()

In [7]:
# import plotly.express as px
# import os
# for i in df.columns:
    
#     fig = px.histogram(
#         df,
#         x=i,
#         color='Diagnosis',                    # Only two colors based on disease
#         title=f'{i} Distribution by Diagnosis Status',
#         labels={i: i, 'count': 'Number of Patients'},
#         color_discrete_map={
#             0: '#636EFA',   # Blue - no Diagnosis
#             1: "#54F389"    # Red   - Has Diagnosis
#             # If your DiseaseLabel is 'No'/'Yes':
#             # 'No': '#636EFA', 'Yes': '#EF553B'
#         },
#         barmode='overlay',          # Overlapping for better comparison
#         opacity=0.75,               # Transparency to see overlapping bars
#         nbins=20,                   # Adjust number of bins as needed
#         text_auto=True              # Show count on bars
#     )

#     fig.update_layout(
#         xaxis_title=i,
#         yaxis_title='Number of Patients',
#         template='plotly_white',
#         height=560,
#         title_font_size=24,
#         title_x=0.5,                    # Center the title
#         legend_title_text='Diagnosis Status',
#         bargap=0.01,
#         barmode='overlay'
#     )

#     fig.update_traces(
#         marker_line_color='white',
#         marker_line_width=1
#     )

#     os.makedirs('features', exist_ok=True)
#     fig.show()
#     fig.write_image(f'features/{i}_Diagnosis_Status.png')

## clearning data set

In [8]:
df.isnull().sum(), df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1659 entries, 0 to 1658
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PatientID                      1659 non-null   int64
 1   Age                            1659 non-null   int64
 2   Gender                         1659 non-null   int64
 3   Ethnicity                      1659 non-null   int64
 4   SocioeconomicStatus            1659 non-null   int64
 5   EducationLevel                 1659 non-null   int64
 6   BMI                            1659 non-null   float64
 7   Smoking                        1659 non-null   int64
 8   AlcoholConsumption             1659 non-null   float64
 9   PhysicalActivity               1659 non-null   float64
 10  DietQuality                    1659 non-null   float64
 11  SleepQuality                   1659 non-null   float64
 12  FamilyHistoryKidneyDisease     1659 non-null   int64
 13  FamilyHistoryHypertension      1659 non-null   int64
 14  FamilyHistoryDiabetes          1659 non-null   int64
 15  PreviousAcuteKidneyInjury      1659 non-null   int64
 16  UrinaryTractInfections         1659 non-null   int64
 17  SystolicBP                     1659 non-null   int64
 18  DiastolicBP                    1659 non-null   int64
 19  FastingBloodSugar              1659 non-null   float64
 20  HbA1c                          1659 non-null   float64
 21  SerumCreatinine                1659 non-null   float64
 22  BUNLevels                      1659 non-null   float64
 23  GFR                            1659 non-null   float64
 24  ProteinInUrine                 1659 non-null   float64
 25  ACR                            1659 non-null   float64
 26  SerumElectrolytesSodium        1659 non-null   float64
 27  SerumElectrolytesPotassium     1659 non-null   float64
 28  SerumElectrolytesCalcium       1659 non-null   float64
 29  SerumElectrolytesPhosphorus    1659 non-null   float64
 30  HemoglobinLevels               1659 non-null   float64
 31  CholesterolTotal               1659 non-null   float64
 32  CholesterolLDL                 1659 non-null   float64
 33  CholesterolHDL                 1659 non-null   float64
 34  CholesterolTriglycerides       1659 non-null   float64
 35  ACEInhibitors                  1659 non-null   int64
 36  Diuretics                      1659 non-null   int64
 37  NSAIDsUse                      1659 non-null   float64
 38  Statins                        1659 non-null   int64
 39  AntidiabeticMedications        1659 non-null   int64
 40  Edema                          1659 non-null   int64
 41  FatigueLevels                  1659 non-null   float64
 42  NauseaVomiting                 1659 non-null   float64
 43  MuscleCramps                   1659 non-null   float64
 44  Itching                        1659 non-null   float64
 45  QualityOfLifeScore             1659 non-null   float64
 46  HeavyMetalsExposure            1659 non-null   int64
 47  OccupationalExposureChemicals  1659 non-null   int64
 48  WaterQuality                   1659 non-null   int64
 49  MedicalCheckupsFrequency       1659 non-null   float64
 50  MedicationAdherence            1659 non-null   float64
 51  HealthLiteracy                 1659 non-null   float64
 52  Diagnosis                      1659 non-null   int64
 53  DoctorInCharge                 1659 non-null   object
dtypes: float64(30), int64(23), object(1)
memory usage: 700.0+ KB

(PatientID                        0
 Age                              0
 Gender                           0
 Ethnicity                        0
 SocioeconomicStatus              0
 EducationLevel                   0
 BMI                              0
 Smoking                          0
 AlcoholConsumption               0
 PhysicalActivity                 0
 DietQuality                      0
 SleepQuality                     0
 FamilyHistoryKidneyDisease       0
 FamilyHistoryHypertension        0
 FamilyHistoryDiabetes            0
 PreviousAcuteKidneyInjury        0
 UrinaryTractInfections           0
 SystolicBP                       0
 DiastolicBP                      0
 FastingBloodSugar                0
 HbA1c                            0
 SerumCreatinine                  0
 BUNLevels                        0
 GFR                              0
 ProteinInUrine                   0
 ACR                              0
 SerumElectrolytesSodium          0
 SerumElectrolytesPotassium       0
 SerumElectrolytesCalcium         0
 SerumElectrolytesPhosphorus      0
 HemoglobinLevels                 0
 CholesterolTotal                 0
 CholesterolLDL                   0
 CholesterolHDL                   0
 CholesterolTriglycerides         0
 ACEInhibitors                    0
 Diuretics                        0
 NSAIDsUse                        0
 Statins                          0
 AntidiabeticMedications          0
 Edema                            0
 FatigueLevels                    0
 NauseaVomiting                   0
 MuscleCramps                     0
 Itching                          0
 QualityOfLifeScore               0
 HeavyMetalsExposure              0
 OccupationalExposureChemicals    0
 WaterQuality                     0
 MedicalCheckupsFrequency         0
 MedicationAdherence              0
 HealthLiteracy                   0
 Diagnosis                        0
 DoctorInCharge                   0
 dtype: int64,
 None)

In [9]:
df.info()

df = df.drop(['PatientID', 'DoctorInCharge'], axis=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1659 entries, 0 to 1658
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PatientID                      1659 non-null   int64
 1   Age                            1659 non-null   int64
 2   Gender                         1659 non-null   int64
 3   Ethnicity                      1659 non-null   int64
 4   SocioeconomicStatus            1659 non-null   int64
 5   EducationLevel                 1659 non-null   int64
 6   BMI                            1659 non-null   float64
 7   Smoking                        1659 non-null   int64
 8   AlcoholConsumption             1659 non-null   float64
 9   PhysicalActivity               1659 non-null   float64
 10  DietQuality                    1659 non-null   float64
 11  SleepQuality                   1659 non-null   float64
 12  FamilyHistoryKidneyDisease     1659 non-null   int64
 13  FamilyHistoryHypertension      1659 non-null   int64
 14  FamilyHistoryDiabetes          1659 non-null   int64
 15  PreviousAcuteKidneyInjury      1659 non-null   int64
 16  UrinaryTractInfections         1659 non-null   int64
 17  SystolicBP                     1659 non-null   int64
 18  DiastolicBP                    1659 non-null   int64
 19  FastingBloodSugar              1659 non-null   float64
 20  HbA1c                          1659 non-null   float64
 21  SerumCreatinine                1659 non-null   float64
 22  BUNLevels                      1659 non-null   float64
 23  GFR                            1659 non-null   float64
 24  ProteinInUrine                 1659 non-null   float64
 25  ACR                            1659 non-null   float64
 26  SerumElectrolytesSodium        1659 non-null   float64
 27  SerumElectrolytesPotassium     1659 non-null   float64
 28  SerumElectrolytesCalcium       1659 non-null   float64
 29  SerumElectrolytesPhosphorus    1659 non-null   float64
 30  HemoglobinLevels               1659 non-null   float64
 31  CholesterolTotal               1659 non-null   float64
 32  CholesterolLDL                 1659 non-null   float64
 33  CholesterolHDL                 1659 non-null   float64
 34  CholesterolTriglycerides       1659 non-null   float64
 35  ACEInhibitors                  1659 non-null   int64
 36  Diuretics                      1659 non-null   int64
 37  NSAIDsUse                      1659 non-null   float64
 38  Statins                        1659 non-null   int64
 39  AntidiabeticMedications        1659 non-null   int64
 40  Edema                          1659 non-null   int64
 41  FatigueLevels                  1659 non-null   float64
 42  NauseaVomiting                 1659 non-null   float64
 43  MuscleCramps                   1659 non-null   float64
 44  Itching                        1659 non-null   float64
 45  QualityOfLifeScore             1659 non-null   float64
 46  HeavyMetalsExposure            1659 non-null   int64
 47  OccupationalExposureChemicals  1659 non-null   int64
 48  WaterQuality                   1659 non-null   int64
 49  MedicalCheckupsFrequency       1659 non-null   float64
 50  MedicationAdherence            1659 non-null   float64
 51  HealthLiteracy                 1659 non-null   float64
 52  Diagnosis                      1659 non-null   int64
 53  DoctorInCharge                 1659 non-null   object
dtypes: float64(30), int64(23), object(1)
memory usage: 700.0+ KB

## model working

In [10]:
x = df.drop(['Diagnosis'], axis=1)
y = df['Diagnosis']

In [11]:
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from xgboost.sklearn import XGBClassifier
from imblearn.over_sampling import SMOTE
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
import numpy as np

In [12]:
X_train, X_test, y_train , y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [13]:
scaled = StandardScaler()
X_train = scaled.fit_transform(X_train)
X_test = scaled.transform(X_test)

In [14]:
models = {
    "Logistic Regression": LogisticRegression(
        class_weight="balanced", max_iter=1000, random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=100, class_weight="balanced", random_state=42
    ),
    "XGBoost": XGBClassifier(
        n_estimators=100, scale_pos_weight=1,
        use_label_encoder=False, eval_metric="logloss",
        random_state=42, verbosity=0
    ),
    # "SVM": SVC(
    #     kernel="rbf", class_weight="balanced",
    #     probability=True, random_state=42
    # ),
    "KNN": KNeighborsClassifier(n_neighbors=5),

    "dt":DecisionTreeClassifier(criterion='log_loss',max_depth=20),

    "grdi":GradientBoostingClassifier(learning_rate=0.001, n_estimators=100, min_samples_split=0.2),

    'gnb':GaussianNB(var_smoothing=1e-9)
}

In [15]:
# skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
# cv_results = {}
 
# for name, model in models.items():
#     cv_scores = cross_val_score(
#         model, X_train, y_train,
#         cv=skf, scoring="roc_auc", n_jobs=-1
#     )
#     cv_results[name] = cv_scores
#     print(f"\n{name}:")
#     print(f"  CV Accuracy Scores : {cv_results[name]}")
#     print(f"  CV ROC-AUC Scores : {cv_scores.round(4)}")
#     print(f"  Mean  ± Std       : {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

In [16]:
from sklearn.metrics          import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix,
    classification_report, roc_curve
)

In [17]:
 
results = {}
best_model_name = None
best_auc = 0
 
for name, model in models.items():
    print(f"\n{'─'*50}")
    print(f"Model: {name}")
    print(f"{'─'*50}")
 
    # Train
    model.fit(X_train, y_train)

    from sklearn.inspection import permutation_importance

    result = permutation_importance(
        model, X_test, y_test,
        n_repeats=10,
        random_state=42,
        scoring='roc_auc'
    )

    perm_df = pd.DataFrame({
        'Feature':   x.columns,
        'Importance': result.importances_mean,
        'Std':        result.importances_std
    }).sort_values('Importance', ascending=False)

    # print(perm_df)
 
    # Predict
    y_pred      = model.predict(X_test)
    y_pred_prob = model.predict_proba(X_test)[:, 1]
 
    # Metrics
    acc  = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec  = recall_score(y_test, y_pred, zero_division=0)
    f1   = f1_score(y_test, y_pred, zero_division=0)
    auc  = roc_auc_score(y_test, y_pred_prob)
    cm   = confusion_matrix(y_test, y_pred)
    fpr, tpr, _ = roc_curve(y_test, y_pred_prob)
 
    results[name] = {
        "Accuracy" : round(acc,  4),
        "Precision": round(prec, 4),
        "Recall"   : round(rec,  4),
        "F1-Score" : round(f1,   4),
        "fpr"  : fpr,
        "tpr"  : tpr,
        # "CV Mean"  : round(cv_results[name].mean(), 4),
        # "CV Std"   : round(cv_results[name].std(),  4),
    }
 
    print(f"  Accuracy  : {acc:.4f}")
    print(f"  Precision : {prec:.4f}")
    print(f"  Recall    : {rec:.4f}")
    print(f"  F1-Score  : {f1:.4f}")
    print(f"  ROC-AUC   : {auc:.4f}")
    print(f"\n  Confusion Matrix:\n{cm}")
    print(f"\n  Classification Report:\n{classification_report(y_test, y_pred)}")
 
    # Track best model
    if auc > best_auc:
        best_auc = auc
        best_model_name = name

──────────────────────────────────────────────────
Model: Logistic Regression
──────────────────────────────────────────────────
  Accuracy  : 0.7751
  Precision : 0.9573
  Recall    : 0.7890
  F1-Score  : 0.8651
  ROC-AUC   : 0.7970

  Confusion Matrix:
[[ 27  16]
 [ 96 359]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.22      0.63      0.33        43
           1       0.96      0.79      0.87       455

    accuracy                           0.78       498
   macro avg       0.59      0.71      0.60       498
weighted avg       0.89      0.78      0.82       498


──────────────────────────────────────────────────
Model: Random Forest
──────────────────────────────────────────────────
  Accuracy  : 0.9137
  Precision : 0.9137
  Recall    : 1.0000
  F1-Score  : 0.9549
  ROC-AUC   : 0.7992

  Confusion Matrix:
[[  0  43]
 [  0 455]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        43
           1       0.91      1.00      0.95       455

    accuracy                           0.91       498
   macro avg       0.46      0.50      0.48       498
weighted avg       0.83      0.91      0.87       498


──────────────────────────────────────────────────
Model: XGBoost
──────────────────────────────────────────────────

c:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

  Accuracy  : 0.9317
  Precision : 0.9358
  Recall    : 0.9934
  F1-Score  : 0.9638
  ROC-AUC   : 0.7830

  Confusion Matrix:
[[ 12  31]
 [  3 452]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.28      0.41        43
           1       0.94      0.99      0.96       455

    accuracy                           0.93       498
   macro avg       0.87      0.64      0.69       498
weighted avg       0.92      0.93      0.92       498


──────────────────────────────────────────────────
Model: KNN
──────────────────────────────────────────────────
  Accuracy  : 0.9116
  Precision : 0.9152
  Recall    : 0.9956
  F1-Score  : 0.9537
  ROC-AUC   : 0.6543

  Confusion Matrix:
[[  1  42]
 [  2 453]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.02      0.04        43
           1       0.92      1.00      0.95       455

    accuracy                           0.91       498
   macro avg       0.62      0.51      0.50       498
weighted avg       0.86      0.91      0.88       498


──────────────────────────────────────────────────
Model: dt
──────────────────────────────────────────────────
  Accuracy  : 0.9016
  Precision : 0.9375
  Recall    : 0.9560
  F1-Score  : 0.9467
  ROC-AUC   : 0.6408

  Confusion Matrix:
[[ 14  29]
 [ 20 435]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.41      0.33      0.36        43
           1       0.94      0.96      0.95       455

    accuracy                           0.90       498
   macro avg       0.67      0.64      0.66       498
weighted avg       0.89      0.90      0.90       498


──────────────────────────────────────────────────
Model: grdi
──────────────────────────────────────────────────
  Accuracy  : 0.9137
  Precision : 0.9137
  Recall    : 1.0000
  F1-Score  : 0.9549
  ROC-AUC   : 0.7168

  Confusion Matrix:
[[  0  43]
 [  0 455]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        43
           1       0.91      1.00      0.95       455

    accuracy                           0.91       498
   macro avg       0.46      0.50      0.48       498
weighted avg       0.83      0.91      0.87       498


──────────────────────────────────────────────────
Model: gnb
──────────────────────────────────────────────────

c:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

  Accuracy  : 0.9137
  Precision : 0.9274
  Recall    : 0.9824
  F1-Score  : 0.9541
  ROC-AUC   : 0.7237

  Confusion Matrix:
[[  8  35]
 [  8 447]]

  Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.19      0.27        43
           1       0.93      0.98      0.95       455

    accuracy                           0.91       498
   macro avg       0.71      0.58      0.61       498
weighted avg       0.89      0.91      0.90       498

In [18]:
import plotly.graph_objects as go
from sklearn.metrics import auc

for model_name, data in results.items():

    fpr = data['fpr']
    tpr = data['tpr']

    # Skip invalid
    if len(fpr) == 0 or len(tpr) == 0:
        continue

    roc_auc = auc(fpr, tpr)

    # 🔥 NEW FIGURE for each model
    fig = go.Figure()

    # ROC curve
    fig.add_trace(go.Scatter(
        x=fpr,
        y=tpr,
        mode='lines',
        name=f"AUC = {roc_auc:.3f}"
    ))

    # Random line
    fig.add_trace(go.Scatter(
        x=[0, 1],
        y=[0, 1],
        mode='lines',
        line=dict(dash='dash'),
        name='Random'
    ))

    fig.update_layout(
        title=f"ROC Curve - {model_name}",
        xaxis_title="False Positive Rate",
        yaxis_title="True Positive Rate",
        width=700,
        height=500
    )
    fig.write_image(f"roc curve/ROC_Curve_{model_name}.png")
    fig.show()

In [19]:
high_feature = perm_df.nlargest(12, 'Importance')

In [20]:
high_feature

                          Feature  Importance       Std
22                            GFR    0.081963  0.012485
20                SerumCreatinine    0.063976  0.016477
39                          Edema    0.018727  0.005295
18              FastingBloodSugar    0.016489  0.006012
43                        Itching    0.014833  0.003119
16                     SystolicBP    0.013759  0.007534
42                   MuscleCramps    0.010442  0.007452
23                 ProteinInUrine    0.007350  0.007747
21                      BUNLevels    0.006348  0.002697
46  OccupationalExposureChemicals    0.006154  0.003822
4                  EducationLevel    0.005392  0.002141
12      FamilyHistoryHypertension    0.004794  0.002949

In [21]:
best_model_name

'Random Forest'

In [22]:
# import plotly.graph_objects as go

# features    = perm_df['Feature']
# importance  = perm_df['Importance']
# std         = perm_df['Std']

# colors = [f'rgba(55,138,221,{round(1 - i*0.09, 2)})' for i in range(len(features))]

In [23]:
import plotly.graph_objects as go
import pandas as pd
import os

# Assuming perm_df is your existing DataFrame
features    = high_feature['Feature']
importance  = high_feature['Importance']
std         = high_feature['Std']

# --- COLOR FIX ---
# This logic ensures the alpha channel never goes below 0.0
colors = [f'rgba(55, 138, 221, {max(0, round(1 - i * 0.09, 2))})' for i in range(len(features))]

fig1 = go.Figure(go.Bar(
    x=importance,
    y=features,
    orientation='h',
    marker_color=colors,
    text=[f"{v:.4f}" for v in importance],
    textposition='outside',
    cliponaxis=False,
))

fig1.update_layout(
    title="Feature Importance — Horizontal Bar",
    xaxis_title="Importance score",
    # Added a check for max(importance) to handle empty data gracefully
    xaxis=dict(range=[0, (max(importance) if len(importance) > 0 else 1) * 1.2]),
    yaxis=dict(categoryorder='total ascending'),
    template='plotly_white',
    height=450,
    showlegend=False,
    margin=dict(l=20, r=50, t=50, b=50) # Added right margin so text isn't cut off
)

# --- DIRECTORY FIX ---
# Create the folder if it doesn't exist to prevent write_image from failing
output_dir = "perm_for_features"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Save and show
# fig1.show()
fig1.write_image(f"{output_dir}/importance_horizontal_bar.png", width=900, height=450, scale=2)

In [24]:
fig2 = go.Figure(go.Bar(
    x=importance,
    y=features,
    orientation='h',
    marker_color=colors,
    text=[f"{v:.4f}" for v in importance],
    textposition='outside',
    cliponaxis=False,
    error_x=dict(
        type='data',
        array=std,
        visible=True,
        color='#e24b4a',
        thickness=2,
        width=6,
    ),
))

fig2.update_layout(
    title="Feature Importance — With Std Error Bars",
    xaxis_title="Importance ± Std Error",
    xaxis=dict(range=[0, max(importance) * 1.25]),
    yaxis=dict(categoryorder='total ascending'),
    template='plotly_white',
    height=450,
    showlegend=False,
)

fig2.write_image("perm_for_features/error_bars.png", width=900, height=450, scale=2)
fig2.show()

In [72]:
fig3 = go.Figure()

# stems (lines from 0 to dot)
for i, (feat, val) in enumerate(zip(features, importance)):
    fig3.add_shape(
        type='line',
        x0=0, x1=val,
        y0=feat, y1=feat,
        line=dict(color='#b5d4f4', width=2),
    )

# dots
fig3.add_trace(go.Scatter(
    x=importance,
    y=features,
    mode='markers+text',
    marker=dict(size=14, color=colors, line=dict(width=1, color='white')),
    text=[f"{v:.4f}" for v in importance],
    textposition='middle right',
    textfont=dict(size=11),
))

fig3.update_layout(
    title="Feature Importance — Dot / Lollipop Chart",
    xaxis_title="Importance score",
    xaxis=dict(range=[-0.002, max(importance) * 1.3]),
    yaxis=dict(categoryorder='array', categoryarray=features),
    template='plotly_white',
    height=450,
    showlegend=False,
)

fig3.write_image("perm_for_features/dot_plot.png", width=1500, height=450, scale=2)
fig3.show()

## model combination

In [73]:
import plotly.graph_objects as go
from sklearn.metrics import auc

# 1. Ensure ROC-AUC is a single number, not an array
for model in results:
    if "fpr" in results[model] and "tpr" in results[model]:
        results[model]["ROC-AUC"] = auc(results[model]["fpr"], results[model]["tpr"])

# 2. Setup Radar Chart
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC']
metrics_closed = metrics + [metrics[0]]
models = list(results.keys())
colors = ['#636EFA', '#EF553B', '#00CC96', '#AB63FA']

fig3 = go.Figure()

for model, color in zip(models, colors):
    # Pull the single values for each metric
    vals = [results[model].get(m, 0) for m in metrics]
    vals_closed = vals + [vals[0]] # Close the loop
    
    fig3.add_trace(go.Scatterpolar(
        r=vals_closed,
        theta=metrics_closed,
        fill='toself',
        name=model,
        line=dict(color=color)
    ))

fig3.update_layout(
    title="Model Comparison — Radar Chart",
    polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
    showlegend=True,
    template='plotly_white'
)
fig3.write_image("model_scoring/model_radar.png", width=1500, height=450, scale=2)
fig3.show()

In [78]:
fig1 = go.Figure()
 
for metric in metrics:
    fig1.add_trace(go.Bar(
        name=metric,
        y=models,  # swap here
        x=[results[m][metric] for m in models],  # swap here
        orientation='h',  # 🔥 important
        text=[f"{results[m][metric]:.2%}" for m in models],
        textposition='outside',
        textfont=dict(size=10),
    ))

fig1.update_layout(
    title="Model Comparison — All Metrics",
    barmode='group',
    xaxis=dict(range=[0, 1.15], tickformat='.0%', title='Score'),  # now x-axis is score
    yaxis_title='ML Model',
    legend=dict(orientation='h', yanchor='bottom', y=1.02, x=0),
    height=550,
)

fig1.write_image("model_scoring/model_grouped_bar.png",width=1500, height=530, scale=2,)

In [75]:
import numpy as np

z = [[results[m][metric] for m in models] for metric in metrics]

fig2 = go.Figure(go.Heatmap(
    z=z,
    x=models,
    y=metrics,
    colorscale='Blues',
    zmin=0, zmax=1,
    text=[[f"{v:.3f}" for v in row] for row in z],
    texttemplate="%{text}",
    textfont=dict(size=12),
    colorbar=dict(title='Score', tickformat='.0%'),
))

fig2.update_layout(
    title="Model vs Metric Heatmap",
    xaxis_title='Model',
    yaxis_title='Metric',
    height=400,
    template='plotly_white',
)

fig2.write_image("model_scoring/model_heatmap.png",width=1500, height=450, scale=2,)
print("Saved: chart2_heatmap.png")

Saved: chart2_heatmap.png

In [76]:
from plotly.subplots import make_subplots

fig4 = make_subplots(
    rows=2, cols=3,
    subplot_titles=metrics,
    vertical_spacing=0.18,
    horizontal_spacing=0.08,
)

positions = [(1,1),(1,2),(1,3),(2,1),(2,2)]

for (row, col), metric in zip(positions, metrics):
    vals = [results[m][metric] for m in models]
    fig4.add_trace(
        go.Bar(
            x=models,
            y=vals,
            marker_color=colors,
            text=[f"{v:.2f}" for v in vals],
            textposition='outside',
            showlegend=False,
        ),
        row=row, col=col,
    )
    fig4.update_yaxes(range=[0, 1.15], tickformat='.0%', row=row, col=col)

fig4.update_layout(
    title="Per-Metric Breakdown",
    height=700,
    template='plotly_white',
)

fig4.write_image("model_scoring/model_subplots.png", width=1500, height=500, scale=2)
print("Saved: chart4_subplots.png")

Saved: chart4_subplots.png

In [30]:
perm_df

                          Feature  Importance       Std
22                            GFR    0.081963  0.012485
20                SerumCreatinine    0.063976  0.016477
39                          Edema    0.018727  0.005295
18              FastingBloodSugar    0.016489  0.006012
43                        Itching    0.014833  0.003119
16                     SystolicBP    0.013759  0.007534
42                   MuscleCramps    0.010442  0.007452
23                 ProteinInUrine    0.007350  0.007747
21                      BUNLevels    0.006348  0.002697
46  OccupationalExposureChemicals    0.006154  0.003822
4                  EducationLevel    0.005392  0.002141
12      FamilyHistoryHypertension    0.004794  0.002949
29               HemoglobinLevels    0.004508  0.002519
5                             BMI    0.004365  0.004417
44             QualityOfLifeScore    0.004247  0.002656
41                 NauseaVomiting    0.004160  0.001401
9                     DietQuality    0.004084  0.003135
1                          Gender    0.003680  0.002633
17                    DiastolicBP    0.003164  0.003499
10                   SleepQuality    0.002448  0.002435
25        SerumElectrolytesSodium    0.002428  0.001344
33       CholesterolTriglycerides    0.002320  0.001757
30               CholesterolTotal    0.002188  0.001432
35                      Diuretics    0.002024  0.001859
19                          HbA1c    0.001738  0.002491
2                       Ethnicity    0.001697  0.003888
38        AntidiabeticMedications    0.001600  0.001149
26     SerumElectrolytesPotassium    0.001329  0.000555
0                             Age    0.001324  0.000342
7              AlcoholConsumption    0.001252  0.001282
14      PreviousAcuteKidneyInjury    0.000961  0.002844
6                         Smoking    0.000797  0.003978
45            HeavyMetalsExposure    0.000746  0.002831
3             SocioeconomicStatus    0.000613  0.000815
8                PhysicalActivity    0.000414  0.000279
40                  FatigueLevels    0.000245  0.001804
36                      NSAIDsUse    0.000031  0.000810
37                        Statins    0.000026  0.002682
32                 CholesterolHDL   -0.000179  0.003771
15         UrinaryTractInfections   -0.000189  0.008105
24                            ACR   -0.000204  0.002742
50                 HealthLiteracy   -0.000210  0.001390
34                  ACEInhibitors   -0.000245  0.000268
48       MedicalCheckupsFrequency   -0.000470  0.001329
27       SerumElectrolytesCalcium   -0.000613  0.001461
13          FamilyHistoryDiabetes   -0.000818  0.002262
49            MedicationAdherence   -0.001038  0.000545
28    SerumElectrolytesPhosphorus   -0.001094  0.001110
31                 CholesterolLDL   -0.001758  0.001334
47                   WaterQuality   -0.002315  0.000343
11     FamilyHistoryKidneyDisease   -0.023828  0.035894

In [31]:
from sklearn.metrics import mutual_info_score
from scipy.stats import entropy
import numpy as np
import pandas as pd

In [32]:
def feature_divergence(X, y):
    classes = np.unique(y)
    c1, c2 = classes[0], classes[1]
    
    divergence_scores = {}

    for col in X.columns:
        # Get probability distributions
        p = X[y == c1][col].value_counts(normalize=True)
        q = X[y == c2][col].value_counts(normalize=True)
        
        # Align indexes
        all_idx = p.index.union(q.index)
        p = p.reindex(all_idx, fill_value=1e-9)
        q = q.reindex(all_idx, fill_value=1e-9)
        
        # KL divergence
        kl_div = entropy(p, q)
        
        divergence_scores[col] = kl_div

    return pd.DataFrame(divergence_scores.items(), columns=['Feature', 'Divergence'])

In [33]:
from sklearn.feature_selection import mutual_info_classif

In [34]:
mi_scores = mutual_info_classif(x, y)

mi_df = pd.DataFrame({
    'Feature': x.columns,
    'MI Score': mi_scores
})

In [35]:
def goodness_factor(div_df, mi_df):
    result = pd.merge(div_df, mi_df, on='Feature')
    result['Goodness Factor (G)'] = result['Divergence'] * result['MI Score']
    return result

In [53]:
# Step 1: Divergence
div_df = feature_divergence(x, y)

# Step 2: Mutual Information
mi_scores = mutual_info_classif(x, y)
mi_df = pd.DataFrame({
    'Feature': x.columns,
    'MI Score': mi_scores
})

# Step 3: Goodness Factor
final_df = goodness_factor(div_df, mi_df)

print(final_df.sort_values(by='Goodness Factor (G)', ascending=False))

                          Feature  Divergence  MI Score  Goodness Factor (G)
20                SerumCreatinine   15.817945  0.023041         3.644540e-01
22                            GFR   15.817945  0.016343         2.585165e-01
36                      NSAIDsUse   15.817945  0.013335         2.109251e-01
18              FastingBloodSugar   15.817945  0.012216         1.932260e-01
23                 ProteinInUrine   15.817945  0.011825         1.870522e-01
8                PhysicalActivity   15.817945  0.010828         1.712757e-01
32                 CholesterolHDL   15.817945  0.010102         1.597900e-01
21                      BUNLevels   15.817945  0.009362         1.480808e-01
25        SerumElectrolytesSodium   15.817945  0.008848         1.399556e-01
30               CholesterolTotal   15.817945  0.008313         1.315021e-01
9                     DietQuality   15.817945  0.006665         1.054321e-01
19                          HbA1c   15.817945  0.005698         9.012803e-02
41                 NauseaVomiting   15.817945  0.005294         8.373283e-02
33       CholesterolTriglycerides   15.817945  0.005011         7.926216e-02
27       SerumElectrolytesCalcium   15.817945  0.004900         7.751018e-02
43                        Itching   15.817945  0.003453         5.461966e-02
42                   MuscleCramps   15.817945  0.002311         3.655589e-02
29               HemoglobinLevels   15.817945  0.002275         3.598325e-02
7              AlcoholConsumption   15.817945  0.001607         2.542072e-02
16                     SystolicBP    0.497025  0.012685         6.304701e-03
17                    DiastolicBP    0.257690  0.002868         7.389535e-04
11     FamilyHistoryKidneyDisease    0.019543  0.004741         9.265129e-05
3             SocioeconomicStatus    0.011851  0.003483         4.127578e-05
39                          Edema    0.018792  0.002147         4.033639e-05
4                  EducationLevel    0.022909  0.001446         3.311850e-05
12      FamilyHistoryHypertension    0.003458  0.006012         2.079170e-05
46  OccupationalExposureChemicals    0.001477  0.009912         1.464046e-05
6                         Smoking    0.004951  0.001372         6.794736e-06
47                   WaterQuality    0.002303  0.000998         2.299929e-06
1                          Gender    0.011939  0.000107         1.282846e-06
14      PreviousAcuteKidneyInjury    0.000196  0.003426         6.722776e-07
34                  ACEInhibitors    0.000120  0.000810         9.690568e-08
2                       Ethnicity    0.002274  0.000000         0.000000e+00
0                             Age    0.281085  0.000000         0.000000e+00
10                   SleepQuality   15.817945  0.000000         0.000000e+00
15         UrinaryTractInfections    0.008432  0.000000         0.000000e+00
13          FamilyHistoryDiabetes    0.001302  0.000000         0.000000e+00
5                             BMI   15.817945  0.000000         0.000000e+00
26     SerumElectrolytesPotassium   15.817945  0.000000         0.000000e+00
31                 CholesterolLDL   15.817945  0.000000         0.000000e+00
28    SerumElectrolytesPhosphorus   15.817945  0.000000         0.000000e+00
24                            ACR   15.817945  0.000000         0.000000e+00
38        AntidiabeticMedications    0.001395  0.000000         0.000000e+00
40                  FatigueLevels   15.817945  0.000000         0.000000e+00
35                      Diuretics    0.005453  0.000000         0.000000e+00
37                        Statins    0.000339  0.000000         0.000000e+00
44             QualityOfLifeScore   15.817945  0.000000         0.000000e+00
45            HeavyMetalsExposure    0.000714  0.000000         0.000000e+00
48       MedicalCheckupsFrequency   15.817945  0.000000         0.000000e+00
49            MedicationAdherence   15.817945  0.000000         0.000000e+00
50                 HealthLiteracy   15.817945  0.000000         0.000000e+00

In [54]:
high_final_df = final_df.nlargest(17, 'Goodness Factor (G)')

In [67]:
import plotly.express as px

# Sort by Goodness Factor
final_df_sorted = high_final_df.sort_values(
    by="Goodness Factor (G)", ascending=False
)

fig = px.scatter(
    final_df_sorted,
    x="Feature",
    y="Goodness Factor (G)",
    color="Goodness Factor (G)",
    size="Goodness Factor (G)",
    size_max=30,
    color_continuous_scale="viridis",
    
    title="📊 Goodness Factor Between Features of CKD Dataset",
    
    labels={
        "Feature": "Features",
        "Goodness Factor (G)": "Goodness Factor Score"
    }
)

fig.update_traces(
    mode='lines+markers',
    marker=dict(line=dict(width=1.5, color='black')),
    line=dict(width=2),
    hovertemplate="<b>%{x}</b><br>G: %{y:.4f}<extra></extra>"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    xaxis=dict(tickangle=-45),
    hovermode="x unified"
)

fig.show()
fig.write_image("perm_for_features/Goodness Factor Score.png", width=1500, height=450, scale=2)

In [68]:
import plotly.express as px

fig = px.scatter(
    final_df_sorted,
    x="Feature",
    y="Goodness Factor (G)",
    color="Goodness Factor (G)",
    size="Goodness Factor (G)",
    title="Goodness Factor between Features of CKD Data"

)

fig.update_traces(mode='lines+markers')

fig.update_layout(
    template="plotly_white"
)

fig.update_xaxes(tickangle=-45)

fig.show()
fig.write_image("perm_for_features/Goodness Factor Score1.png", width=1500, height=450, scale=2)

In [70]:
import plotly.express as px

# Sort by Goodness Factor
final_df_sorted = high_final_df.sort_values(
    by="Goodness Factor (G)", ascending=False
)

fig = px.scatter(
    final_df_sorted,
    x="Feature",
    y="Divergence",
    color="Divergence",
    size="Divergence",
    size_max=20,
    color_continuous_scale="plasma",
    
    title="📊 Divergence Factor Between Features of CKD Dataset",
    
    labels={
        "Feature": "Features",
        "Divergence Factor (G)": "Divergence Factor Score"
    }
)

fig.update_traces(
    mode='lines+markers',
    marker=dict(line=dict(width=1.5, color='black')),
    line=dict(width=2),
    hovertemplate="<b>%{x}</b><br>G: %{y:.4f}<extra></extra>"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    xaxis=dict(tickangle=-45),
    hovermode="x unified"
)

fig.show()
fig.write_image(
    "perm_for_features/Divergence_Factor_Score.png",
    width=1600,
    height=450,
    scale=2)

In [71]:
import plotly.express as px

fig = px.scatter(
    final_df_sorted,
    x="Feature",
    y="Divergence",
    color="Divergence",
    size="Divergence",
    title="Divergence Factor between Features of CVD Data"

)

fig.update_traces(mode='lines+markers')

fig.update_layout(
    template="plotly_white"
)

fig.update_xaxes(tickangle=-45)

fig.show()
fig.write_image("perm_for_features/Divergence Factor Score1.png", width=1500, height=450, scale=2)